* set research directory
cd "~\Thanos"

* use "dat_w.dta" generated by data_extract.R
use "thanos_wide_v2_2.dta"

reshape long p_wt intv intv_dt age reg div mar adl3_ adl5_ iadl3_ iadl5_ ///
cesd srh lim_work bmi back hosp hosp_stays hosp_nights nh nh_stays ///
nh_nights nh_now nh_yr nh_mo nh_days doc doc_visits hhc meds surg ///
dent shf med_exp adl_walk adl_dress adl_bath adl_eat adl_bed adl_toilet ///
iadl_map iadl_calc iadl_tel iadl_money iadl_meds iadl_shop iadl_meals ///
mob lg_mus gross_mot fine_mot bp diab cancer lung heart stroke psych ///
arth cc ulc vig vig_freq lt lt_freq mod_freq alc_ev alc_days alc_drinks ///
smoke_ev smoke_cur cesd_depr cesd_eff cesd_sleep cesd_happy cesd_lone ///
cesd_sad cesd_going cesd_enjoy nh_wt prob75yo mprob mprobev alz dem srm pastmem ///
ir10w ir20w dr10w dr20w ss c20b c86b name_mo name_dmo name_yr name_dwk ///
name_sci name_cac name_pres name_vp vocab tr20w tr40w tm, i(id) j(wave)

* save long-format data
save thanos_long_v2_2 , replace
